spring:
    application:
        name: spring-security-demo-new

    datasource:
        url: jdbc:mysql://localhost:3306/security_demo_new
        username: root
        password: sum93917
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

    security:
        user:
            name: admin
            password: 12345
            roles: ADMIN
